name: Create Release and Deploy

on:
  schedule:
    - cron: '28 7 * * *'  # 매일 7시 25분 (UTC) 실행 (한국 시간 16시 25분)
  push:
    branches:
      - dev  # dev 브랜치에서만 실행

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get the version from package.json
        id: get_version
        run: |
          VERSION=$(cat package.json | jq -r .version)
          NOTES=$(cat package.json | jq -r .releaseNotes)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "NOTES=$NOTES" >> $GITHUB_ENV

      - name: Debugging environment variables
        run: |
          echo "Version: $VERSION"
          echo "Release Notes: $NOTES"

      # 릴리스가 이미 존재하는지 확인하고, 존재하지 않으면 생성
      - name: Check if release exists
        id: check_release
        run: |
          EXISTING_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.VERSION }}" \
            | jq -r '.message')
          if [[ "$EXISTING_RELEASE" == "Not Found" ]]; then
            echo "Release does not exist, creating it."
            echo "create_release=true" >> $GITHUB_ENV
          else
            echo "Release already exists."
            echo "create_release=false" >> $GITHUB_ENV
          fi

      # 릴리스가 존재하지 않으면 GitHub Release 생성
      - name: Create GitHub Release
        if: env.create_release == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Release ${{ env.VERSION }}"
          body: ${{ env.NOTES }}

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Create and push Releases branch if it does not exist
        run: |
          git fetch origin
          if ! git rev-parse --verify origin/Releases; then
            echo "Releases branch does not exist. Creating it..."
            git checkout -b Releases
            git push origin Releases
          else
            echo "Releases branch already exists."
          fi

      - name: Merge dev branch into main
        run: |
          git checkout main
          git merge dev --no-ff -m "Merging dev into main"
          git push origin main
